### PR TITLE
Release v0.1.0a0

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@webknjaz Could you drop in the PyPI key? Also, if possible, it would be nice to rename the project without the underscore, for consistency with other projects.

**Comment by webknjaz** [comment]
> Also, if possible, it would be nice to rename the project without the underscore, for consistency with other projects.

Not all of the projects use dashes, though. FWIW the dist name is controlled with whatever is in `setup.cfg`. PyPI, pip and the rest of the ecosystem apply normalization. Though, I'm not sure that it's possible to update the canonical dist name on PyPI. Anyway, it should be possible to use either dash or underscore when installing with pip.

**Comment by webknjaz** [comment]
It seems like PyPI's canonical form might already be dashed internally.

**Comment by webknjaz** [comment]
Alright, the secret has been provisioned.

**Pull request merged**
