### PR TITLE
Cache permissions during request

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
**Problem**

When making some calls, we make dozens of permission checks (which may involve fetching the user's permissions from the DB each time). For example, a list call that returns 10 results with 10 attributes on each would probably have 101 checks (1 for the list call itself, 1 for each attribute of each result).

**Solution**

If we can cache the fetched permissions for the duration of a request, we can ensure each call only needs 1 DB request to complete the permission checks.

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
@webknjaz Could you have a quick glance at this and let me know what your thoughts are?

The solution doesn't work currently, because `Request` is not hashable. So, I'm wondering if you have any ideas on a better solution, or whether we can consider making it hashable in aiohttp to support this use case?

**Comment by webknjaz** [comment]
Not sure. I guess caching the HTTP request object would not be a good idea since it represents I/O streams and the unread bits of data are in file descriptors. Maybe you should work on marshaling requests into some immutable objects in this lib instead.

**Comment by Dreamsorcerer** [comment]
Working on another PR, I've now made the callback without the request object (expecting the user to include the resources they need with `partial(get_permissions, db_connection)` or similar). So, maybe I can just make a wrapper that uses the request id?
```
@lrucache(10)
def _get_permissions(cache_id: int, identity: str):
    return get_permissions_callback(identity)

def get_permissions(request, identity):
    return self._get_permissions(id(request), identity)
```

Or similar...

**Comment by webknjaz** [comment]
I don't feel confident giving architectural advice on this project since I do not have experience with it so I guess it's up to you 🤷‍♂️

**Comment by Dreamsorcerer** [comment]
I also just thought that the ID is not unique and could easily be reused. Now I'm thinking a middleware can just add a random unique ID to each request (or lazily set it in this function if it's not already set) and use that as the cache key.

**Comment by Dreamsorcerer** [comment]
I was being dumb, simpler solution is to just cache the permissions on the request object directly. No need for lrucache or anything like that.

**Pull request merged**
